### ISSUE TITLE
Catch error in parsing unusual Youtube URLs

### ISSUE THREAD

**Issue by kat-kel** [medialab/ural#120]
When parsing Youtube URLs, one of the first things the function `parse_youtube_url()` does is split the string into parts including a `path`, which is the third result of `urlsplit(url)`. Many of the following actions depend on the variable `path` and further split it up, often using the function `urlpathsplit(path)`.

https://github.com/medialab/ural/blob/492d0f37deded61b7a1e005bd6025add3a693f16/ural/youtube.py#L162-L166

The issue is that sometimes what looks like (or even is) a valid Youtube URL does not have a path that splits into multiple parts. For example, the valid URL `https://youtube.com/user/` has the path `/user/`. But the function `urlpathsplit()` returns a list of `['user']`.

Currently, the way to get the user name from the split path will face an index error with the input URL `https://youtube.com/user/` because the list does not have an index 1.
https://github.com/medialab/ural/blob/492d0f37deded61b7a1e005bd6025add3a693f16/ural/youtube.py#L164

This sort of thing risks happening most times when a value is parsed from the split path using an index. It might be a good idea to add an Exception to catch the (albeit rare) index error.

**Comment by kat-kel** [comment]
To reproduce the error, you can observe the effect on this URL:

```python
from ural.youtube import parse_youtube.url
url = "https://youtube.com/channel/"
parsed - parse_youtube_url(url)
```

It sends this error (instead of None):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kelly.christensen/.pyenv/versions/dev-ural/lib/python3.10/site-packages/ural/youtube.py", line 175, in parse_youtube_url
    cid = urlpathsplit(path)[1]
IndexError: list index out of range
```

From what I can tell, it's because the path is incomplete. Youtube wants something to follow `"channel/"`, though it's still considered a valid URL (and it gets a good response from the server).

The same error can `IndexError`, however, for valid Youtube pages. For example, the abbreviated channel path `c/` is usually completed by the name of the channel which follows. However, it is possible for someone to have a channel called `"c"`, which would not be followed by anything. The name of the channel would be misread as an incomplete path and therefore send the same `IndexError`, even though it's a valid URL for the youtube channel.
