### ISSUE TITLE
LRUTrie.match crashes on IP urls

### ISSUE THREAD

**Issue by boogheta** [medialab/ural#63]
Example:
http://127.0.0.1/economie/2019/01/08/un-journaliste-poursuit-richard-ferrand-pour-lavoir-bloque-sur-twitter/

```
Traceback (most recent call last):
  File "bin/export_users_urls_lrumedia.py", line 56, in <module>
    media = trie.match(l) or ""
  File "/home/boo/.virtualenvs/gazouilloire-polarisation/lib/python2.7/site-packages/ural/lru/trie.py", line 33, in match
    stems = self.__lru_stems(url)
  File "/home/boo/.virtualenvs/gazouilloire-polarisation/lib/python2.7/site-packages/ural/lru/stems.py", line 93, in lru_stems
    return lru_stems_from_parsed_url(urlsplit(full_url), tld_aware=tld_aware)
  File "/home/boo/.virtualenvs/gazouilloire-polarisation/lib/python2.7/site-packages/ural/lru/stems.py", line 49, in lru_stems_from_parsed_url
    tld = '.'.join(domain_parts[non_zero_i:])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by Yomguithereal** [comment]
I should also try ipv6 and localhost

**Comment by boogheta** [comment]
I have the same crash on a well looking url:
`ERROR: LRUtrie matching crashes for url http://black.bl <type 'exceptions.TypeError'> 'NoneType' object has no attribute '__getitem__'`

**Comment by boogheta** [comment]
One more: http://cuts.An
